name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-document:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
          
    - name: Set up Python environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
        pip install pytest sphinx

    - name: Build compiled_gibbs
      run: |
        source venv/bin/activate
        python src/spin_sampler/compile_gibbs.py  

    - name: Debug compiled_gibbs
      run: |
        ls -l src/spin_sampler
        ls -l 

    - name: Install package
      run: |
        source venv/bin/activate
        pip install .


    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
        

    - name: Generate documentation
      run: |
        source venv/bin/activate
        cd docs
        sphinx-build -b html . _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html


    # - name: Upload documentation
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: documentation
    #     path: docs/_build/html/

